name: deploy
on:
  push:
      branches:
        - master
env:
  dockerimage: 'mha2002mad/sa-frontend'
 
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: fetch
      uses: actions/checkout@v3

    - name: nodeSetup
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: installDeps
      run: npm ci || npm install

    - name: buildForProd
      run: npm run build

    - name: dockerLogIn
      uses: docker/login-action@v3
      with:
        username: ${{secrets.docker_usr}}
        password: ${{ secrets.docker_psw }}

    - name: buildDockerImage
      run: |
        docker build -t $dockerimage:latest .

    - name: PushToHub
      run: |
        docker push $dockerimage:latest 

    - name: sshAndDeploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.stuatte_frontend_host }}
        username: ${{ secrets.stuatte_frontend_host_user }}
        key: ${{ secrets.stuatte_pem_key }}
        script: |
          sudo -i
          sudo docker stop SAF
          sudo docker rm SAF
          sudo docker pull mha2002mad/sa-frontend
          sudo docker run -d --name SAF -p 443:443 \
          -v /etc/letsencrypt/archive/abcdef444.duckdns.org/fullchain1.pem:/etc/nginx/certs/fullchain.pem \
          -v /etc/letsencrypt/archive/abcdef444.duckdns.org/privkey1.pem:/etc/nginx/certs/privkey.pem \
          mha2002mad/sa-frontend
